version: '2.4'

services:
  postgres-server:
    image: postgres:${POSTGRES_VERSION:-11.1}
    environment:
      POSTGRES_DB: wallet_daemon_test1
      POSTGRES_USER: ledger
      POSTGRES_PASSWORD: ledger_secret
    healthcheck:
      test: "pg_isready -h localhost -p 5432 -U ledger -d postgres"
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 30s
    ports:
      - "5432:5432"
  wallet-daemon:
    image: ledgerhq/ledger-wallet-daemon:alpha-pg-1
    environment:
      CORE_DATABASE_ENGINE: postgres
      CORE_PG_USER: ledger
      CORE_PG_PWD: ledger_secret
      CORE_PG_HOST: postgres-server
      CORE_PG_PORT: 5432
      CORE_PG_DB_NAME_PREFIX: wallet_daemon_
    entrypoint: /app/run.sh -Dscala.concurrent.context.numThreads=x8 -Dscala.concurrent.context.maxThreads=x8
    healthcheck:
      test: "command -v curl && curl -fsS -H 'pubKey: 0327015350DF6FA1CFAFA8FFD09307724EE3F723A07D5EBD26646796E4A64DC550' http://wallet-daemon:9200/_health"
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 1m
    ports:
      - "9200:9200"
    depends_on:
      - postgres-server
